// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    partial class GameStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameStore.Models.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");
                });

            modelBuilder.Entity("GameStore.Models.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b1d7a14-6f01-4f2d-b4b2-2a3461f9f701"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("9c3d67b9-5cc8-48cc-b4bb-9c2f30bf24aa"),
                            Name = "RTS",
                            ParentGenreId = new Guid("2b1d7a14-6f01-4f2d-b4b2-2a3461f9f701")
                        },
                        new
                        {
                            Id = new Guid("a0d0fe2a-b588-4c36-941b-3e14970b5237"),
                            Name = "TBS",
                            ParentGenreId = new Guid("2b1d7a14-6f01-4f2d-b4b2-2a3461f9f701")
                        },
                        new
                        {
                            Id = new Guid("e7c2e5a0-6b06-4785-9b65-2f57a3c0f1d2"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("c1bde7c2-1b0a-46ef-9a54-0c882c5c9c11"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("1e0e2f11-2b2b-4f5f-8b0e-50ed3d70ed1c"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("9e9b6f40-7b4d-4cf9-93a9-bc0e2f594c85"),
                            Name = "Rally",
                            ParentGenreId = new Guid("1e0e2f11-2b2b-4f5f-8b0e-50ed3d70ed1c")
                        },
                        new
                        {
                            Id = new Guid("87c7e2d0-8f9c-4e52-946a-0d0b8f8af879"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("1e0e2f11-2b2b-4f5f-8b0e-50ed3d70ed1c")
                        },
                        new
                        {
                            Id = new Guid("4c1b90ac-5c2c-4a56-a357-236f8380b40b"),
                            Name = "Formula",
                            ParentGenreId = new Guid("1e0e2f11-2b2b-4f5f-8b0e-50ed3d70ed1c")
                        },
                        new
                        {
                            Id = new Guid("b7412f02-90c1-4fbb-95b8-bc90d1b4f3d0"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("1e0e2f11-2b2b-4f5f-8b0e-50ed3d70ed1c")
                        },
                        new
                        {
                            Id = new Guid("e9f7c2a4-fb9e-4f1f-9d3f-6a4f3b14bd6c"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("b2f95f0b-bb3a-4d82-9f5a-4a31f2c2a8a4"),
                            Name = "FPS",
                            ParentGenreId = new Guid("e9f7c2a4-fb9e-4f1f-9d3f-6a4f3b14bd6c")
                        },
                        new
                        {
                            Id = new Guid("9d47a4b2-6f1e-4f5a-8d8b-ef8228f52f11"),
                            Name = "TPS",
                            ParentGenreId = new Guid("e9f7c2a4-fb9e-4f1f-9d3f-6a4f3b14bd6c")
                        },
                        new
                        {
                            Id = new Guid("0b5c97c5-1f41-4cb1-b968-7e7f1a12f702"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("ea1a5e5a-8f3f-4a88-9806-7ff0a9e9f2cc"),
                            Name = "Puzzle & Skill"
                        });
                });

            modelBuilder.Entity("GameStore.Models.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cc03e69-7a7b-4a08-bc79-7db7a4b7b08c"),
                            Type = "Mobile"
                        },
                        new
                        {
                            Id = new Guid("c0864f05-19d8-4d02-9c9b-2f25b2e1cb28"),
                            Type = "Browser"
                        },
                        new
                        {
                            Id = new Guid("a51b02b3-2d1f-4b9b-8f38-8a1f7f0abde3"),
                            Type = "Desktop"
                        },
                        new
                        {
                            Id = new Guid("0e6c8b5f-0e69-4c1c-8d2b-5d1a4a7b2d4f"),
                            Type = "Console"
                        });
                });

            modelBuilder.Entity("GameStore.Models.GameGenre", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Models.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Models.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Models.Platform", "Platform")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Models.Genre", b =>
                {
                    b.HasOne("GameStore.Models.Genre", "ParentGenre")
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Models.Genre", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Models.Platform", b =>
                {
                    b.Navigation("GamePlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
